### ISSUE TITLE
"end" is marked as similar

### ISSUE THREAD

**Issue by reedstonefood** [codeclimate/codeclimate-duplication#155] opened 2016-12-05 23:53 UTC
This line
`str << '*' * (w+2) << " #{je[4]}"`
is showing as being similar to
`end`

[Source](https://codeclimate.com/github/reedstonefood/machi_koro/lib/machi_koro/databank.rb)

Am I missing something here?

**Comment by maxjacobson** [comment] 2016-12-06 19:39
@reedstonefood Hi, thanks for opening this issue. It's really helpful to have a reproduction case when coming across bugs like this.

I can tell you that the engine is mis-reporting the line numbers, and is actually trying to tell you that [lines 95 and 96](https://github.com/reedstonefood/machi_koro/blob/affe488952f274c35236c80b50309b46f9133c5a/lib/machi_koro/databank.rb#L95-L96) are similar.

This file reproduces the bug:

```ruby
# foo.rb
def console_output
  w = 36 # width of "card"
  str = '*' * (w+2) + "\n"
  str << '*' << self.roll_range.center(w) << "* #{je[0]}\n"
  str << '*' << @attribute["name"].capitalize.center(w) << "* #{je[1]}\n"
  str << '*' << " Symbol : #{@attribute["symbol"]} ".center(w) << "* #{je[2]}\n"
  str << '*' << " Cost : #{@attribute["cost"]} ".center(w) << "* #{je[3]}\n"
  str << '*' * (w+2) << " #{je[4]}"
  puts str.colour(ansi_colour)
end
```

But this one doesn't:

```ruby
# foo.rb
def console_output
  w = 36 # width of "card"
  str = '*' * (w+2) + ""
  str << '*' << self.roll_range.center(w) << "* #{je[0]}"
  str << '*' << @attribute["name"].capitalize.center(w) << "* #{je[1]}"
  str << '*' << " Symbol : #{@attribute["symbol"]} ".center(w) << "* #{je[2]}"
  str << '*' << " Cost : #{@attribute["cost"]} ".center(w) << "* #{je[3]}"
  str << '*' * (w+2) << " #{je[4]}"
  puts str.colour(ansi_colour)
end
```

It seems to be thrown off by the newline characters in the string literals when coming up with the line numbers. We'll look into where that's happening and try to have a fix out as soon as we can.

**Comment by reedstonefood** [comment] 2016-12-09 13:02
Happy to help! The explanation makes perfect sense.

**Comment by zenspider** [comment] 2017-02-03 00:58
Yes, line numbers and strings (esp w/ heredocs or interpolation) are a mess.

**Comment by zenspider** [comment] 2017-02-03 01:02
This should be fixed with a newer version of ruby_parser:

### 3.8.3 / 2016-10-09

* 1 minor enhancement:

  * Support Ruby 2.1 number literals. (soutaro)

* 3 bug fixes:

  * **Fixed line numbers for strs with backslash-newlines. (maxjacobson)**
  * Improved compatibility on tokenizing number. (soutaro)
  * Refactored and fixed multiline array line numbers. (ptoomey3, with changes)

**Comment by dblandin** [comment] 2017-03-14 20:34
@zenspider @maxjacobson Awesome work!

@reedstonefood I'm going to go ahead and close this issue. Feel free to reopen if you're still getting the same similar to `end` issues.

Thanks!

**Closed by dblandin** 2017-03-14 20:34 UTC
