### ISSUE TITLE
Ruby 2.0 Keyword Arguments

### ISSUE THREAD

**Issue by jelder** [codeclimate/codeclimate-duplication#52] opened 2015-12-16 20:34 UTC
This crashes on any file using Ruby 2.0 keyword arguments.

`app/models/question.rb`:
```ruby
class Question < ActiveRecord::Base
  # 12 more lines
  flexible_slugs_from :prompt, max_length: 200
end
```

```
Skipping file ./app/models/question.rb due to exception
(Racc::ParseError) ./app/models/question.rb:13 :: parse error on value ":" (tCOLON) /opt/jruby/lib/ruby/stdlib/racc/parser.rb:539:in `on_error'
/usr/local/bundle/gems/ruby_parser-3.7.2/lib/ruby_parser_extras.rb:1124:in `on_error'
com/headius/racc/Cparse.java:709:in `_racc_do_parse_c'
/opt/jruby/lib/ruby/stdlib/racc/parser.rb:271:in `do_parse'
/usr/local/bundle/gems/ruby_parser-3.7.2/lib/ruby_parser_extras.rb:1036:in `block in process'
org/jruby/ext/timeout/Timeout.java:115:in `timeout'
/usr/local/bundle/gems/ruby_parser-3.7.2/lib/ruby_parser_extras.rb:1024:in `process'
/usr/local/bundle/gems/ruby_parser-3.7.2/lib/ruby_parser_extras.rb:1362:in `block in process'
org/jruby/RubyArray.java:1560:in `each'
/usr/local/bundle/gems/ruby_parser-3.7.2/lib/ruby_parser_extras.rb:1360:in `process'
/usr/src/app/lib/cc/engine/analyzers/ruby/main.rb:27:in `process_file'
/usr/src/app/lib/cc/engine/analyzers/analyzer_base.rb:10:in `run'
/usr/src/app/lib/cc/engine/analyzers/reporter.rb:30:in `block in process_files'
/usr/src/app/lib/cc/engine/analyzers/file_thread_pool.rb:22:in `block in run'
Skipping file ./app/models/concerns/report_validations.rb due to exception
(RubyParser::SyntaxError) Odd number (2) list for Hash. s(:array, s(:call, nil, :action)) /usr/local/bundle/gems/ruby_parser-3.7.2/lib/ruby_parser_extras.rb:128:in `syntax_error'
/usr/local/bundle/gems/ruby_parser-3.7.2/lib/ruby18_parser.rb:5688:in `_reduce_492'
com/headius/racc/Cparse.java:709:in `_racc_do_parse_c'
/opt/jruby/lib/ruby/stdlib/racc/parser.rb:271:in `do_parse'
/usr/local/bundle/gems/ruby_parser-3.7.2/lib/ruby_parser_extras.rb:1036:in `block in process'
org/jruby/ext/timeout/Timeout.java:115:in `timeout'
/usr/local/bundle/gems/ruby_parser-3.7.2/lib/ruby_parser_extras.rb:1024:in `process'
/usr/local/bundle/gems/ruby_parser-3.7.2/lib/ruby_parser_extras.rb:1362:in `block in process'
org/jruby/RubyArray.java:1560:in `each'
/usr/local/bundle/gems/ruby_parser-3.7.2/lib/ruby_parser_extras.rb:1360:in `process'
/usr/src/app/lib/cc/engine/analyzers/ruby/main.rb:27:in `process_file'
/usr/src/app/lib/cc/engine/analyzers/analyzer_base.rb:10:in `run'
/usr/src/app/lib/cc/engine/analyzers/reporter.rb:30:in `block in process_files'
/usr/src/app/lib/cc/engine/analyzers/file_thread_pool.rb:22:in `block in run'
/usr/src/app/node_modules/babylon/lib/parser/location.js:27
  throw err;
  ^

SyntaxError: Unexpected token (126:5)
    at Parser.pp.raise (/usr/src/app/node_modules/babylon/lib/parser/location.js:24:13)
    at Parser.pp.unexpected (/usr/src/app/node_modules/babylon/lib/parser/util.js:91:8)
    at Parser.pp.expect (/usr/src/app/node_modules/babylon/lib/parser/util.js:85:33)
    at Parser.pp.parseCallExpressionArguments (/usr/src/app/node_modules/babylon/lib/parser/expression.js:334:12)
    at Parser.pp.parseSubscripts (/usr/src/app/node_modules/babylon/lib/parser/expression.js:306:29)
    at Parser.pp.parseExprSubscripts (/usr/src/app/node_modules/babylon/lib/parser/expression.js:277:15)
    at Parser.pp.parseMaybeUnary (/usr/src/app/node_modules/babylon/lib/parser/expression.js:247:19)
    at Parser.pp.parseExprOps (/usr/src/app/node_modules/babylon/lib/parser/expression.js:178:19)
    at Parser.pp.parseMaybeConditional (/usr/src/app/node_modules/babylon/lib/parser/expression.js:160:19)
    at Parser.pp.parseMaybeAssign (/usr/src/app/node_modules/babylon/lib/parser/expression.js:123:19)
/usr/src/app/node_modules/babylon/lib/parser/location.js:27
  throw err;
  ^

SyntaxError: Unexpected token (9:19)
    at Parser.pp.raise (/usr/src/app/node_modules/babylon/lib/parser/location.js:24:13)
    at Parser.pp.unexpected (/usr/src/app/node_modules/babylon/lib/parser/util.js:91:8)
    at Parser.pp.parseClassProperty (/usr/src/app/node_modules/babylon/lib/parser/statement.js:786:50)
    at Parser.pp.parseClassBody (/usr/src/app/node_modules/babylon/lib/parser/statement.js:698:34)
    at Parser.pp.parseClass (/usr/src/app/node_modules/babylon/lib/parser/statement.js:641:8)
    at Parser.pp.parseExport (/usr/src/app/node_modules/babylon/lib/parser/statement.js:856:19)
    at Parser.pp.parseStatement (/usr/src/app/node_modules/babylon/lib/parser/statement.js:137:90)
    at Parser.pp.parseBlockBody (/usr/src/app/node_modules/babylon/lib/parser/statement.js:529:25)
    at Parser.pp.parseTopLevel (/usr/src/app/node_modules/babylon/lib/parser/statement.js:31:8)
    at Parser.parse (/usr/src/app/node_modules/babylon/lib/parser/index.js:98:17)
/usr/src/app/node_modules/babylon/lib/parser/location.js:27
  throw err;
  ^

SyntaxError: Unexpected token (8:19)
    at Parser.pp.raise (/usr/src/app/node_modules/babylon/lib/parser/location.js:24:13)
    at Parser.pp.unexpected (/usr/src/app/node_modules/babylon/lib/parser/util.js:91:8)
    at Parser.pp.parseClassProperty (/usr/src/app/node_modules/babylon/lib/parser/statement.js:786:50)
    at Parser.pp.parseClassBody (/usr/src/app/node_modules/babylon/lib/parser/statement.js:698:34)
    at Parser.pp.parseClass (/usr/src/app/node_modules/babylon/lib/parser/statement.js:641:8)
    at Parser.pp.parseExport (/usr/src/app/node_modules/babylon/lib/parser/statement.js:856:19)
    at Parser.pp.parseStatement (/usr/src/app/node_modules/babylon/lib/parser/statement.js:137:90)
    at Parser.pp.parseBlockBody (/usr/src/app/node_modules/babylon/lib/parser/statement.js:529:25)
    at Parser.pp.parseTopLevel (/usr/src/app/node_modules/babylon/lib/parser/statement.js:31:8)
    at Parser.parse (/usr/src/app/node_modules/babylon/lib/parser/index.js:98:17)
/usr/src/app/node_modules/babylon/lib/parser/location.js:27
  throw err;
  ^

SyntaxError: Unexpected token (8:19)
    at Parser.pp.raise (/usr/src/app/node_modules/babylon/lib/parser/location.js:24:13)
    at Parser.pp.unexpected (/usr/src/app/node_modules/babylon/lib/parser/util.js:91:8)
    at Parser.pp.parseClassProperty (/usr/src/app/node_modules/babylon/lib/parser/statement.js:786:50)
    at Parser.pp.parseClassBody (/usr/src/app/node_modules/babylon/lib/parser/statement.js:698:34)
    at Parser.pp.parseClass (/usr/src/app/node_modules/babylon/lib/parser/statement.js:641:8)
    at Parser.pp.parseExport (/usr/src/app/node_modules/babylon/lib/parser/statement.js:856:19)
    at Parser.pp.parseStatement (/usr/src/app/node_modules/babylon/lib/parser/statement.js:137:90)
    at Parser.pp.parseBlockBody (/usr/src/app/node_modules/babylon/lib/parser/statement.js:529:25)
    at Parser.pp.parseTopLevel (/usr/src/app/node_modules/babylon/lib/parser/statement.js:31:8)
    at Parser.parse (/usr/src/app/node_modules/babylon/lib/parser/index.js:98:17)
/usr/src/app/node_modules/babylon/lib/parser/location.js:27
  throw err;
  ^

SyntaxError: Unexpected token (8:19)
    at Parser.pp.raise (/usr/src/app/node_modules/babylon/lib/parser/location.js:24:13)
    at Parser.pp.unexpected (/usr/src/app/node_modules/babylon/lib/parser/util.js:91:8)
    at Parser.pp.parseClassProperty (/usr/src/app/node_modules/babylon/lib/parser/statement.js:786:50)
    at Parser.pp.parseClassBody (/usr/src/app/node_modules/babylon/lib/parser/statement.js:698:34)
    at Parser.pp.parseClass (/usr/src/app/node_modules/babylon/lib/parser/statement.js:641:8)
    at Parser.pp.parseExport (/usr/src/app/node_modules/babylon/lib/parser/statement.js:856:19)
    at Parser.pp.parseStatement (/usr/src/app/node_modules/babylon/lib/parser/statement.js:137:90)
    at Parser.pp.parseBlockBody (/usr/src/app/node_modules/babylon/lib/parser/statement.js:529:25)
    at Parser.pp.parseTopLevel (/usr/src/app/node_modules/babylon/lib/parser/statement.js:31:8)
    at Parser.parse (/usr/src/app/node_modules/babylon/lib/parser/index.js:98:17)
/usr/src/app/node_modules/babylon/lib/parser/location.js:27
  throw err;
  ^

SyntaxError: Unexpected token (7:19)
    at Parser.pp.raise (/usr/src/app/node_modules/babylon/lib/parser/location.js:24:13)
    at Parser.pp.unexpected (/usr/src/app/node_modules/babylon/lib/parser/util.js:91:8)
    at Parser.pp.parseClassProperty (/usr/src/app/node_modules/babylon/lib/parser/statement.js:786:50)
    at Parser.pp.parseClassBody (/usr/src/app/node_modules/babylon/lib/parser/statement.js:698:34)
    at Parser.pp.parseClass (/usr/src/app/node_modules/babylon/lib/parser/statement.js:641:8)
    at Parser.pp.parseExport (/usr/src/app/node_modules/babylon/lib/parser/statement.js:856:19)
    at Parser.pp.parseStatement (/usr/src/app/node_modules/babylon/lib/parser/statement.js:137:90)
    at Parser.pp.parseBlockBody (/usr/src/app/node_modules/babylon/lib/parser/statement.js:529:25)
    at Parser.pp.parseTopLevel (/usr/src/app/node_modules/babylon/lib/parser/statement.js:31:8)
    at Parser.parse (/usr/src/app/node_modules/babylon/lib/parser/index.js:98:17)
```

**Comment by wfleming** [comment] 2015-12-18 01:34
Hi @jelder,

Any chance you can share the rest of that file? The snippet you included parses correctly for me, so I don't think it's the specifically the `max_length: 200` syntax causing problems by itself. The behavior is probably affected by other content earlier in the file.

This engine uses the [RubyParser](https://github.com/seattlerb/ruby_parser) under the hood for parsing. If you have a snippet that you can share that reproduces the errors, we'd certainly want to investigate ourselves, but you might want to file an issue with that project as well, as I'm sure the maintainers would appreciate it.

Thanks!

**Comment by alduethadyn** [comment] 2016-01-13 15:14
@wfleming did you ever figure this out? We are now seeing the same types of errors on our project, which was passing fine last week.

**Comment by jelder** [comment] 2016-01-13 15:50
@wfleming The 12 omitted lines are all `include SomeConcern` and I don't think I can reasonably share those.

**Comment by wfleming** [comment] 2016-01-13 20:08
@jelder The actual module contents shouldn't affect the parse results, just the content of `question.rb`. If you're not comfortable sharing that publicly, would you be comfortable sharing it privately by emailing will@codeclimate.com? I've tried several variations on keyword args in source files and the current version of the `RubyParser` gem has handled them.

**Comment by wfleming** [comment] 2016-01-13 20:16
@alduethadyn [`RubyParser`](https://github.com/seattlerb/ruby_parser) is not, unfortunately, 100% accurate. We haven't changed the version used recently: the latest version was released in October. Have you started using Ruby 2.3 and some of its new syntax by any chance? I know that the parser gem has not been updated to support that syntax yet.

That said, these sorts of parse errors also should not affect whether or not your analysis passes: when the parsing fails for a file we print the error and continue with the next file, precisely because the parsers aren't 100% accurate. If you're seeing failures from this engine on your analysis, can you share details about the error code (this will be shown at the top of the page for the build on codeclimate.com) and the error output from the engine? Feel free to email me at will@codeclimate.com if you'd rather not post any details here.

**Comment by wfleming** [comment] 2016-03-31 19:25
We've been unable to reproduce this behavior, and `RubyParser` does handle the usages of keyword arguments we've tried. This issue is fairly stale at this point, and the faulty behavior, if it still exists, is in [`RubyParser`](https://github.com/seattlerb/ruby_parser), so that project would be a more appropriate place to discuss the issue. Closing this issue for now.

**Closed by wfleming** 2016-03-31 19:25 UTC
